// SPDX-FileCopyrightText: 2026 André Fiedler
// SPDX-License-Identifier: AGPL-3.0-or-later

import path from 'node:path'
import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'
import { ServerAssetVersioner } from './ServerAssetVersioner.mjs'

const noStoreCacheControl = 'no-store, no-cache, must-revalidate, max-age=0'

/**
 * Builds an Apache/shared-hosting frontend artifact from the browser source
 * tree by applying the same version rewrites as the deployment workflow.
 */
export class StaticDeployBuilder {
    /**
     * Copies and rewrites the browser source tree into one deploy directory.
     * @param {{ projectRoot: string, sourceRoot: string, outputRoot: string }} options
     * @returns {Promise<{ version: string, outputRoot: string }>}
     */
    static async build(options) {
        const projectRoot = path.resolve(String(options?.projectRoot || ''))
        const sourceRoot = path.resolve(String(options?.sourceRoot || ''))
        const outputRoot = path.resolve(String(options?.outputRoot || ''))
        const version = await StaticDeployBuilder.readAppVersion(projectRoot)

        StaticDeployBuilder.#assertSafeOutputPath(sourceRoot, outputRoot)

        await StaticDeployBuilder.copySourceTree(sourceRoot, outputRoot)
        await StaticDeployBuilder.rewriteStaticAssets(outputRoot, version)
        await StaticDeployBuilder.writeApacheCachePolicy(outputRoot)

        return { version, outputRoot }
    }

    /**
     * Reads the package version used as the static asset cache key.
     * @param {string} projectRoot
     * @returns {Promise<string>}
     */
    static async readAppVersion(projectRoot) {
        const packageRaw = await readFile(
            path.join(projectRoot, 'package.json'),
            'utf8'
        )
        const pkg = JSON.parse(packageRaw)
        return String(pkg?.version || '').trim()
    }

    /**
     * Copies the browser source tree to a clean output directory.
     * @param {string} sourceRoot
     * @param {string} outputRoot
     * @returns {Promise<void>}
     */
    static async copySourceTree(sourceRoot, outputRoot) {
        await rm(outputRoot, { force: true, recursive: true })
        await mkdir(path.dirname(outputRoot), { recursive: true })
        await cp(sourceRoot, outputRoot, {
            recursive: true,
            filter: (sourcePath) =>
                !StaticDeployBuilder.#isIgnoredDeploySource(sourcePath)
        })
    }

    /**
     * Rewrites index.html and local module imports with the app version key.
     * @param {string} outputRoot
     * @param {string} version
     * @returns {Promise<void>}
     */
    static async rewriteStaticAssets(outputRoot, version) {
        const indexPath = path.join(outputRoot, 'index.html')
        const indexHtml = await readFile(indexPath, 'utf8')
        const modulePaths = await StaticDeployBuilder.#collectMatchingFiles(
            outputRoot,
            (filePath) => filePath.endsWith('.mjs')
        )

        await writeFile(
            indexPath,
            ServerAssetVersioner.rewriteHtmlDocument(indexHtml, version)
        )
        await Promise.all(
            modulePaths.map((modulePath) =>
                StaticDeployBuilder.#rewriteJavaScriptModule(
                    modulePath,
                    version
                )
            )
        )
    }

    /**
     * Writes root Apache cache headers for hosts that serve the artifact
     * without the local Node server's no-store response headers.
     * @param {string} outputRoot
     * @returns {Promise<void>}
     */
    static async writeApacheCachePolicy(outputRoot) {
        await writeFile(
            path.join(outputRoot, '.htaccess'),
            StaticDeployBuilder.buildApacheCachePolicy()
        )
    }

    /**
     * Builds the Apache cache policy text for static deploys.
     * @returns {string}
     */
    static buildApacheCachePolicy() {
        return (
            '# Generated by npm run build:static.\n' +
            '<IfModule mod_headers.c>\n' +
            '    <FilesMatch "\\.(?:html|css|mjs|js|json|wasm|svg)$">\n' +
            '        Header set Cache-Control "' +
            noStoreCacheControl +
            '"\n' +
            '    </FilesMatch>\n' +
            '</IfModule>\n'
        )
    }

    /**
     * Rewrites one JavaScript module file in place.
     * @param {string} modulePath
     * @param {string} version
     * @returns {Promise<void>}
     */
    static async #rewriteJavaScriptModule(modulePath, version) {
        const source = await readFile(modulePath, 'utf8')
        await writeFile(
            modulePath,
            ServerAssetVersioner.rewriteJavaScriptModule(source, version)
        )
    }

    /**
     * Recursively collects files matching a predicate.
     * @param {string} directory
     * @param {(filePath: string) => boolean} predicate
     * @returns {Promise<string[]>}
     */
    static async #collectMatchingFiles(directory, predicate) {
        const entries = await readdir(directory, { withFileTypes: true })
        const nestedFiles = await Promise.all(
            entries.map(async (entry) => {
                const entryPath = path.join(directory, entry.name)
                if (entry.isDirectory()) {
                    return StaticDeployBuilder.#collectMatchingFiles(
                        entryPath,
                        predicate
                    )
                }

                if (entry.isFile() && predicate(entryPath)) {
                    return [entryPath]
                }

                return []
            })
        )

        return nestedFiles.flat()
    }

    /**
     * Returns true for files that should not be uploaded to shared hosting.
     * @param {string} sourcePath
     * @returns {boolean}
     */
    static #isIgnoredDeploySource(sourcePath) {
        const baseName = path.basename(sourcePath)
        return (
            baseName === '.DS_Store' ||
            baseName === '.env' ||
            baseName.startsWith('.env.')
        )
    }

    /**
     * Guards against deleting the source tree or filesystem root.
     * @param {string} sourceRoot
     * @param {string} outputRoot
     * @returns {void}
     */
    static #assertSafeOutputPath(sourceRoot, outputRoot) {
        const filesystemRoot = path.parse(outputRoot).root

        if (!outputRoot || outputRoot === filesystemRoot) {
            throw new Error('Refusing to write static deploy output at root.')
        }

        if (outputRoot === sourceRoot) {
            throw new Error('Refusing to overwrite the source directory.')
        }

        if (sourceRoot.startsWith(outputRoot + path.sep)) {
            throw new Error('Refusing to write output above the source tree.')
        }
    }
}
